### ISSUE TITLE
blDownloadData fails on OSX

### ISSUE THREAD

**Issue by Besler** [Bonelab/Bonelab#16]
@njneeteson pointed this out.

```bash
(bl) njneeteson@Nathans-MacBook-Pro ~ % blDownloadData
DownloadData:
  url               https://github.com/Bonelab/BonelabData/trunk/data/
  output_directory  /Users/njneeteson/.bldata
  no_verify         False

Locations:
  url:              https://github.com/Bonelab/BonelabData/trunk/data/
  output_directory: /Users/REDACTED/.bldata
Are these locations OK? [y/n]: y
svn: error: The subversion command line tools are no longer provided by Xcode.
[ERROR] Could not execute download. Do you have SVN installed?
(bl) njneeteson@Nathans-MacBook-Pro ~ %
```

Sounds like SVN is not included anymore so we need a good solution.

**Comment by njneeteson** [comment]
Workaround:

1. Install brew: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
2. Download SVN: `brew install svn`
3. blDownloadData will work again

**Comment by njneeteson** [comment]
blDownloadData is broken again.

```
blDownloadData
DownloadData:
  url               https://github.com/Bonelab/BonelabData/trunk/data/
  output_directory  /Users/nathanneeteson/.bldata
  no_verify         False

Locations:
  url:              https://github.com/Bonelab/BonelabData/trunk/data/
  output_directory: /Users/nathanneeteson/.bldata
Are these locations OK? [y/n]: y
svn: E170013: Unable to connect to a repository at URL 'https://github.com/Bonelab/BonelabData/trunk/data'
svn: E160013: '/Bonelab/BonelabData/trunk/data' path not found
[ERROR] Could not execute download. Do you have SVN installed?
```

I do have `svn` installed. Something is broken with using `svn` to download from github and I can't fix it. Could be something github did to make this just not work anymore?

Probably what needs to happen is all of this tests data should be moved to zenodo and the `blDownloadData` and related code should be updated, but I don't have time to do this right now. But until this is done the tests will fail.
